baseurl = "https://uzimihsr.github.io"
DefaultContentLanguage = "en"
title = "meow.md"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
author = false
googleAnalytics = "UA-146479727-1"

[Params]
  subtitle = "にゃーん"
  logo = "/images/sotochan_icon.jpg" # Expecting square dimensions
  #favicon = "img/favicon.ico"
  favicon = "/images/sotochan_icon.jpg"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "uzimihsr"
  github = "uzimihsr"
  twitter = "uzimihsr"
  instagram = "uzimihsr"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3
